name: Domain Interior Studio
favicon: null
layout_spectrum: 0.2951618854422122
typography_spectrum: 0.45693893311545253
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d0c4c8'
    - '#8e5649'
    - '#867677'
    - '#564b47'
    - '#332524'
  brandStrength: 0.4375
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
