name: Domain Interior Studio
favicon: null
layout_spectrum: 0.2951618854422122
typography_spectrum: 0.45693893311545253
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4625553600490093
  lightness: 0.39366888208314776
  saturation: 0.5055495565757155
  rhythmicContrast: 0.8228160950820893
purpose: []
